### ISSUE TITLE
NANDY_Create a new Emacs file

### ISSUE THREAD

**Issue by debjanee-nandy** [birkenkrahe/ds205_22#10]
![Nandy_Create a Emacs File](https://user-images.githubusercontent.com/98052248/150850250-6df91560-9c0a-4f7c-aa46-8187f3992edc.png)

**Comment by birkenkrahe** [comment]
Hi - I think you need to rename the file to .emacs - otherwise it looks good. Don't know where the 2 missing bits went though (your file size is 943 bit while it should be 945).
