### ISSUE TITLE
.emacs file made

### ISSUE THREAD

**Issue by nicholas-chaney** [birkenkrahe/ds205_22#11]
![Screenshot (3)](https://user-images.githubusercontent.com/89215818/150867792-7216e9c9-42db-4a0b-9af6-f65844982456.png)

**Comment by birkenkrahe** [comment]
The only problem here is that GNU Emacs when it opens may not find the .emacs file unless you load it explicitly (and then Windows may screw with you anyway) - you got to put it into the $HOME directory (~/). I doubt that c:.../Downloads is $HOME.
