### ISSUE TITLE
.emacs file created

### ISSUE THREAD

**Issue by Mollymellor** [birkenkrahe/ds205_22#13]
![Emacs Screenshot](https://user-images.githubusercontent.com/89222125/150869446-5fb30522-a930-4b77-a2af-6b71145981e9.png)

**Comment by birkenkrahe** [comment]
Two issues here: a) the file must be called .emacs - otherwise Emacs will not recognize it as initialization file. 2) It must be in the $HOME folder (Open Emacs and go to the $HOME directory to find out where that is). I don't know if Emacs opens to /Desktop but I doubt it.
