### ISSUE TITLE
create.emacs-Connor

### ISSUE THREAD

**Issue by Tra1n3rR3D** [birkenkrahe/ds205_22#16]
![Screenshot 2022-01-24 155223](https://user-images.githubusercontent.com/89218496/150872250-35d77dce-647f-4901-a7a6-9ce49ee3f34d.png)

**Comment by birkenkrahe** [comment]
The only problem here is that GNU Emacs when it opens may not find the .emacs file unless you load it explicitly (and then Windows may screw with you anyway) - you got to put it into the $HOME directory (~/).
