### ISSUE TITLE
Fortunato emacs done

### ISSUE THREAD

**Issue by fortuhf** [birkenkrahe/ds205_22#18]
![Screenshot 2022-01-24 160909](https://user-images.githubusercontent.com/89221615/150873318-09cdd929-b522-476e-a175-67fed59afb6c.png)

**Comment by birkenkrahe** [comment]
The only problem here is that GNU Emacs when it opens may not find the .emacs file unless you load it explicitly (and then Windows may screw with you anyway) - you got to put it into the $HOME directory (~/).
