### ISSUE TITLE
Blake Huffman - Delayed Learning (II)

### ISSUE THREAD

**Issue by BlakeZFH** [birkenkrahe/ds205_22#46]
Case Study: Delayed Learning (II)

Main Message: 
Though using Tidy to teach R to computer science students may have its merits, it is less intuitive for non-programmers and requires a greater knowledge of programming to use. Because of this, Tidy should not be pushed onto non-programmers; instead, they should just be taught base-R.

Content: 
In base-R, the code is:
                             thue2 <- subset(Thuesen,blood.glucose < 7)
whereas in Tidy, the same code is:
		             library(dplyr)
			     thue2 <- thue2 %>% filter(blood.glucose < 7)

In order to teach a new student this code in base-R, the student would only really need an understanding of basic variable assignment and of the ‘subset’ function. To teach the student this code in Tidy, however, would require the student to have an understanding of libraries, variable assignment, the filter function, and pipelining. While this extra knowledge might be useful for a computer science student, a non-programmer who only wants to use the programming for more basic processes would have no use for this. In addition to this, trying to learn four new things at once while also having no coding experience can lead to overload. This is problematic for 2 reasons— 1: It makes learning something new even harder because there is too much information to absorb at once. 2: It can easily overwhelm new users, driving them away from programming in an increasingly digital age.

Personal Views: 
I think that the essay as a whole and this case study in particular offer a great perspective on an issue plaguing the programming world: Even as technology becomes more integrated into our lives, programming and computer science still seems just as separated from everyday non-programmers as it was decades ago. While greater variability in use and greater abstraction may ultimately help programmers and computer scientists, the rest of the population only gets further driven from technology as it becomes harder and harder to be a beginner. Because of this, I absolutely agree that base-R would be a much better option than Tidyverse for teaching non-programmers more basic processes for everyday use.

**Comment by birkenkrahe** [comment]
Excellent insight, thank you, and useful to me, too, as I'm preparing a talk on similar issues. I may even cite you. This is very well put: 

> Even as technology becomes more integrated into our lives, programming and computer science still seems just as separated from everyday non-programmers as it was decades ago. While greater variability in use and greater abstraction may ultimately help programmers and computer scientists, the rest of the population only gets further driven from technology as it becomes harder and harder to be a beginner.
