### ISSUE TITLE
Debjanee Nandy - Case Studies I & II (Delayed Learning)

### ISSUE THREAD

**Issue by debjanee-nandy** [birkenkrahe/ds205_22#53]
After reading the article by R legend Norman Matloff, I have decided to write about the first two case studies - especially since I am a non-coder who is trying to learn R as a data analytics tool. I chose two studies instead of one since they convey the same core message. The main message of the case studies for me is that it is not a good idea to start learning R with Tidyverse as an absolute beginner.  Rather, a complete beginner (with no prior coding experience) should learn to use base-R first and then go into Tidyverse because of complexity and delayed learning.
In Case Study I, the author argues that people who start with Base-R learn faster and better than Tidyverse people. Moreover, functions from the Tidyverse package do not cover everything that a beginner should absolutely learn. The author used vectors and vector subscripts as an example. Since Tidyers do not focus on vectors that much, the learners sometimes do not learn to use them efficiently. In the second Case Study, the author argues that Tidyverse codes are too complex to understand - something that would be very simple in Base R. The syntax is also very different. For a beginner, it would be a lot of operators to memorize. As a result, learning Tidyverse first slows down a learner's progress.
As a beginner learner myself, I completely agree with the author. I am taking my very first data science course, and I am not a CS major. I have a very little coding background. I am probably the least experienced student in class in terms of coding exposure. I can vow that if I were to learn Tidyverse first, it would have been very difficult and confusing for me. Since I started with Base R first, I got to learn all the basics before jumping into a package like Tidyverse. Although Tidyverse can be more efficient for data visualization, it is best to start with Base R in my opinion.

**Comment by birkenkrahe** [comment]
Debjanee, for someone without coding experience, you're doing very well!
