### ISSUE TITLE
Ben Grafton issue submission to confirm completion

### ISSUE THREAD

**Issue by benjamingrafton** [birkenkrahe/ds205_22#7]
Hopefully this demonstrates my account is working correctly. Attached a recipe for fun.

[Baked Rigatoni with Beef Recipe](https://github.com/birkenkrahe/ds205/files/7893007/Baked.Rigatoni.with.Beef.Recipe.-.Pillsbury.com.pdf)

**Comment by birkenkrahe** [comment]
Nice touch! Will pass the recipe on to the kitchen!
