### ISSUE TITLE
.emacs file created - Sampley

### ISSUE THREAD

**Issue by jsampley** [birkenkrahe/ds205_22#9]
![emacs_file_creaton_sampley](https://user-images.githubusercontent.com/89150656/150838209-51c96106-1e8c-413d-8da1-f5f305f08014.PNG)

**Comment by birkenkrahe** [comment]
The only problem here is that GNU Emacs when it opens will not find the .emacs file unless you load it explicitly (and then Windows may screw with you anyway) - you got to put it into the $HOME directory (~/).
